/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/communitiesNavigation`; params?: Router.UnknownInputParams; } | { pathname: `/communityDetails`; params?: Router.UnknownInputParams; } | { pathname: `/editEvent`; params?: Router.UnknownInputParams; } | { pathname: `/eventDetails`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/loginForm`; params?: Router.UnknownInputParams; } | { pathname: `/saveEventsContext`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/communities` | `/communities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/createEvent` | `/createEvent`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/savedEvents` | `/savedEvents`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/communitiesNavigation`; params?: Router.UnknownOutputParams; } | { pathname: `/communityDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/editEvent`; params?: Router.UnknownOutputParams; } | { pathname: `/eventDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/loginForm`; params?: Router.UnknownOutputParams; } | { pathname: `/saveEventsContext`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/communities` | `/communities`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/createEvent` | `/createEvent`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/savedEvents` | `/savedEvents`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/communitiesNavigation${`?${string}` | `#${string}` | ''}` | `/communityDetails${`?${string}` | `#${string}` | ''}` | `/editEvent${`?${string}` | `#${string}` | ''}` | `/eventDetails${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/loginForm${`?${string}` | `#${string}` | ''}` | `/saveEventsContext${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/communities${`?${string}` | `#${string}` | ''}` | `/communities${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/createEvent${`?${string}` | `#${string}` | ''}` | `/createEvent${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/savedEvents${`?${string}` | `#${string}` | ''}` | `/savedEvents${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/communitiesNavigation`; params?: Router.UnknownInputParams; } | { pathname: `/communityDetails`; params?: Router.UnknownInputParams; } | { pathname: `/editEvent`; params?: Router.UnknownInputParams; } | { pathname: `/eventDetails`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/loginForm`; params?: Router.UnknownInputParams; } | { pathname: `/saveEventsContext`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/communities` | `/communities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/createEvent` | `/createEvent`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/savedEvents` | `/savedEvents`; params?: Router.UnknownInputParams; };
    }
  }
}
